export default {
    navBar: {
        welcome: 'Welcome',
        accessibilityMenu: 'Accessibility Menu',
        plainLanguage: 'Plain Language',
        accessibility: "Accessibility",
        signLanguage: "Sign Language",
        backToStart: "Back to english start page",
        imageDesc: "Get the information you need to plan your visit",
    },
    sectionIndicator: {
        beforeYouVisit: "Before you visit",
        reachingTheMuseum: "Reaching the museum",
        movingAround: "Moving around",
        experienceTheExhibition: "Experience the exhibition",
        faq: "FAQ",
        visitorStories: "Visitor stories"
    },
    filter: {
        pickTopics: 'Choose topics you want to see:',
        filterInfo: 'We’ll show you info that matches what you pick.',
        addKeyword: 'Add Keyword',
        enterKeyword: 'Enter a custom keyword:',
        options: {
            limitedMobility: 'Limited mobility',
            blindLowVision: 'Blind or low vision',
            deafHardHearing: 'Deaf or hard of hearing',
            cognitiveDifferences: 'Cognitive differences & Neurodivergent',
            cognitiveDifferencesSubtext: 'Neurodiverse people, learning disabilities, etc.'
        },
        "keywords": {
            "crowd": "Crowd",
            "wayfindingSupport": "Wayfinding support",
            "lighting": "Lighting",
            "accessibleExhibitionContent": "Accessible Exhibition content",
            "interactiveElements": "Interactive Elements",
            "qrCodes": "QR-Codes",
            "museumLayout": "Museum Layout",
            "seating": "Seating",
            "accessibleRestrooms": "Accessible Restrooms"
        }
    },
    beforeVisit: {
        title: 'Before you visit',
        note: 'Note:',
        description: 'We welcome visitors with disabilities to the Natural History museum in Karlsruhe. <br aria-hidden=”true”> <br aria-hidden=”true”>Need help planning your visit? <br aria-hidden=”true”>',
        descriptionAppendix: '<br aria-hidden=”true”>We’re here to help with questions about accessibility. <br aria-hidden=”true”> We want your visit to be comfortable.',
        description2: "We're always working to make the museum more accessible. <br aria-hidden=”true”> If you have questions, feedback, or ideas, please contact us:<br aria-hidden=”true”><br aria-hidden=”true”>",
        SLNote: "Sign Language was auto generated by sign.mt and is only for demonstrating purposes for this prototype.",
        languageNote: "This prototype supports only english language for demonstrating purposes.",
        phone: 'Phone: 01234567',
        or: 'or email: ',
        voiceCalls: '(Voice calls are welcome)',
        generalInfo: {
            title: 'General information',
            description: 'We want you to feel welcome during your visit.'
        },
        admission: {
            title: 'Admission & Entry',
            description: 'If you have a disability ID, you pay less to enter. <br aria-hidden=”true”> If the ID contains a “B” or “H”, one person can come with you for free. <br aria-hidden=”true”> You can access everything without stairs.',
        },
        support: {
            title: 'Need support during your visit?',
            description: 'You can find our staff at the main desk by the entrance. <br aria-hidden=”true”>They are there all day. <br aria-hidden=”true”>We don\'t always have someone who knows German Sign Language. <br aria-hidden=”true”>Please tell us before you come if you need sign language support.'
        },
        assistance: {
            title: 'On-site assistance',
            description: 'Our staff can help you move around the museum. <br aria-hidden=”true”> Find places to sit, or use things like elevators. <br aria-hidden=”true”>You can also talk to use before your visit if you need help.'
        },
        visitorVolume: {
            title: 'Visitor volume',
            description: 'The museum is usually busiest on Friday afternoons. <br aria-hidden=”true”> And all day on Saturdays and Sundays. <br aria-hidden=”true”> Weekdays are typically less crowded. <br aria-hidden=”true”> For more details, check the graphic below. <br aria-hidden=”true”> We also offer silent hour events for a calmer experience.',
            link: 'silent hour events'
        },
        specialServices: {
            title: 'Special services',
            silentHours: {
                title: 'Silent hours',
                description: 'We offer silent hours for a calmer visit. <br aria-hidden=”true”>Fewer people are allowed in during this time. <br aria-hidden=”true”>This helps reduce noise and movement. <br aria-hidden=”true”> Silent hours are great for: <br aria-hidden=”true”>' +
                    ' - People who want a more relaxed visit <br aria-hidden=”true”>' +
                    ' - Neurodivergent individuals <br aria-hidden=”true”>' +
                    ' - People with sensory sensitivities <br aria-hidden=”true”>' +
                    'You can see upcoming silent hours in our <a href="https://www.smnk.de/information/veranstaltungskalender/?tx_psbeventmanager_em%5Baction%5D=list&tx_psbeventmanager_em%5Bcontroller%5D=Event&cHash=04b9d8618dac37baf78e42f6fdbd28d9" target="_blank">event calendar</a>.',
                slText: 'Show silent hours in our event calendar'
            },
        }
    },
    reachingTheMuseum: {
        title: "Reaching the museum",
        gettingToMuseum: {
            title: "Getting to the museum",
            description: "The Natural History Museum Karlsruhe is at Friedrichsplatz, in the city center. <br aria-hidden=”true”>" +
                "It’s easy to get to by public transport or car."
        },
        byTrain: {
            title: "By train",
            description: "The museum is easily accessible via barrier-free train. The nearest stations are:",
            stations: {
                marktplatz: "Marktplatz (Lines S1/S11, S2, S5, Tram 1)",
                ettlingerTor: "Ettlinger Tor / Staatstheater (Lines S1/S11, S4, S52, S7, S8, Tram 2)"
            },
            walkDescription: "Both stations are about a 500-meter walk from the museum.<br aria-hidden=”true”>" +
                "For live travel times and access info, check the KVV journey planner."
        },
        byCar: {
            title: "By car",
            description: "If you're driving, take the B10 into the city center. <br aria-hidden=”true”> Then continue onto Kriegsstraße. <br aria-hidden=”true”>" +
                "At Ettlinger Tor, follow signs to Stadtmitte (city center).",
            parking: {
                friedrichsplatz: "Friedrichsplatz (150 meter walk to the museum)",
                landesbibliothek: "Landesbibliothek (150 meter walk to the museum)",
                ihk: "IHK (220 meter walk to the museum)",
                ece: "ECE Ettlinger Tor Center (300 meter walk to museum)"
            }
        },
        detailedDescription: {
            title: "Detailed description",
            byCar: {
                title: "My visit by car",
                description: "My visit to the museum by car frame by frame"
            },
            byTrain: {
                title: "My visit by train",
                description: "My visit to the museum by train frame by frame"
            }
        },
        lockers: {
            title: "Lockers",
            description: "We offer lockers near the entrance. They are behind the entry area. <br aria-hidden=”true”>" +
                "You can safely store your personal items there.<br aria-hidden=”true”>" +
                "To use a locker, you’ll need a 1€ coin. <br aria-hidden=”true”>" +
                "The lockers extend all the way to the floor. <br aria-hidden=”true”>" +
                "Please remember to empty your locker before you leave."
        }
    },
    insideMuseumSteps: {
        step1: {
            caption: "I head to the entry. A ramp for wheelchair access is on the right."
        },
        step2: {
            caption: "I walk into the entry hall. I go the left to the entry desk. I can open the door normally or with the electric door opener on the right."
        },
        step3: {
            caption: "Here, I talk to the staff and ask for a ticket. I can give them my disability card if I have one. Then I pay. Usually the staff only speaks German."
        },
        step4: {
            caption: "When I want to store my belongings I go to the lockers. They are right next to the stairs. There are also the restrooms."
        },
        step5: {
            caption: "Here I can store my belongings. I need a 1 Euro key. The toilets are on the right."
        },
        step6: {
            caption: "The elevator and accessible bathroom are around the corner."
        }
    },
    carSteps: {
        start: {
            step1: {
                caption: "I head to the parking garage \"Parkhaus am Friedrichsplatz\"."
            },
            step2: {
                caption: "I can take the right or left lane. An accessible parking spot is only available on the right lane."
            },
            step3: {
                caption: "Now I can search for a parking spot."
            },
            step4: {
                caption: "This is the layout of the garage. There is one accessible parking spot."
            },
            step5: {
                caption: "I go to the exit in the middle."
            },
            step6: {
                caption: "Later I can use this device for paying. However, it is not easily accessible for wheelchair users. Normally there is a person behind a cash desk on the left who can help."
            },
            step7: {
                caption: "I take the elevator on the right side."
            },
            step8: {
                caption: "I step out of the elevator. I can already see the natural history museum."
            }
        }
    },
    trainSteps: {
        fork: {
            option1: {
                caption: "I exit at the station Marktplatz (Lines S1/S11, S2, S5, Tram 1)."
            },
            option2: {
                caption: "I exit at the station Etllinger Tor / Staatstheater (Lines S1/S11, S4, S52, S7, S8, Tram 2)."
            }
        },
        pathA: {
            step1: {
                caption: "I take the elevator direction ”Ausgang Kriegsstraße, Karl-Friedrichstr. / Ettlinger Tor Center ”."
            },
            step2: {
                caption: "I step outside the elevator and take the next elevator to exit the station."
            },
            step3: {
                caption: "When I exit the station I go to the right and walk 70 meters to the roundabout."
            },
            step4: {
                caption: "In the roundabout I go to the left."
            },
            step5: {
                caption: "I walk down the street until the intersection (140 meter)."
            },
            step6: {
                caption: "I cross the intersection where I can see the natural history museum on the left."
            }
        },
        pathB: {
            step1: {
                caption: "I take the elevator direction \"Marktplatz, Rathaus, Schloss \"."
            },
            step2: {
                caption: "I step outside the elevator and turn to the right."
            },
            step3: {
                caption: "I walk around 30 meters until the first intersection. I turn to the left."
            },
            step4: {
                caption: "I walk around 250 meters until I see the \"Ettlinger Tor \"."
            },
            step5: {
                caption: "I cross two intersections during this way."
            },
            step6: {
                caption: "Now I can already see the natural history museum and turn to the right."
            }
        }
    },
    movingAround: {
        title: "Moving around",
        environmentalConditions: {
            title: "Environmental Conditions",
            lightingAndSensoryComfort: {
                title: "Lighting & sensory comfort",
                description: " Our sensory map shows areas that are: <br aria-hidden=”true”>" +
                    " - Quieter and less crowded <br aria-hidden=”true”>" +
                    " - Lit with natural or artificial light <br aria-hidden=”true”>" +
                    "Use the map to plan a visit that feels right for you."
            },
            spaciousLayout: {
                title: "Spacious layout",
                description: "Our halls and exhibits have lots of space for wheelchairs and walkers.<br aria-hidden=”true”> The entrance has a ramp and automatic doors. <br aria-hidden=”true”> Two large elevators connect all floors and have space for several wheelchairs."
            },
            accessibleSeating: {
                title: "Accessible seating",
                description: "There is seating available throughout the museum. You can use it at any time."
            },
            accessibleRestrooms: {
                title: "Accessible restrooms",
                description: "On the ground floor is an accessible restroom. <br aria-hidden=”true”> You can open it with a Euro key. <br aria-hidden=”true”>You can also ask for one at the front desk. <br aria-hidden=”true”>There is also a care room on the ground floor. It includes: <br aria-hidden=”true”>" +
                    "- A medical couch <br aria-hidden=”true”>" +
                    "- A changing table <br aria-hidden=”true”>",
            }
        },
        navigatingTheMuseum: {
            title: "Navigating the museum",
            museumLayout: {
                title: "Museum Layout",
                description: "The museum has four main areas: <br aria-hidden=”true”>" +
                    "Ground Floor <br aria-hidden=”true”>" +
                    "- Right side: Live reptiles, amphibians, and fish <br aria-hidden=”true”>" +
                    "- Left side: Rhine region’s stones and minerals <br aria-hidden=”true”>" +
                    "Upper Floor <br aria-hidden=”true”>" +
                    "- Left side: Insects and animals <br aria-hidden=”true”>" +
                    "- Right side: Special exhibitions that change over time"
            },
            mobilityFriendlyAccess: {
                title: "Mobility-friendly access",
                description: "The whole museum is easy to access with wheelchairs, walkers, or other mobility aids. <br aria-hidden=”true”>Accessibility features include: <br aria-hidden=”true”>" +
                    " - Step-free access through a ramp at the main entrance <br aria-hidden=”true”>" +
                    " - Automatic door openers at key entry points <br aria-hidden=”true”>" +
                    " - Two elevators that take you to all exhibition areas on both floors <br aria-hidden=”true”>" +
                    "You can see their locations on the museum layout above."
            },
            supportForBlindOrLowVisionVisitors: {
                title: "Navigation for blind or low-vision visitors",
                description: "Tactile markers in the entrance hall and cafeteria help with finding your way. We also have: <br aria-hidden=”true”>" +
                    " - Braille and raised markings on handrails to show floor levels <br aria-hidden=”true”>" +
                    " - Tactile buttons in elevators <br aria-hidden=”true”>" +
                    "Some exhibition areas have limited tactile guidance. <br aria-hidden=”true”>Overall, the tactile guidance is not consistent throughout the museum.<br aria-hidden=”true”>" +
                    "For better support, blind or low-vision visitors may want to: <br aria-hidden=”true”>" +
                    "- Visit with a companion <br aria-hidden=”true”>" +
                    "- Book a guided tour adapted to their needs <br aria-hidden=”true”>"
            }
        }
    },
    experienceTheExhibition: {
        title: "Experience the exhibition",
        intro: "We want everyone to be able to enjoy our exhibitions.",
        interactingWithContent: {
            title: "Interacting with the content"
        },
        learnInDifferentWays: {
            title: "Learn in Different Ways",
            description: "Many parts of the exhibition can be enjoyed without reading. For example you can: <br aria-hidden=”true”>" +
                "- Watch marine life in the aquariums <br aria-hidden=”true”>" +
                "- Explore colors and textures in the geology section <br aria-hidden=”true”>" +
                "If you want to learn more, we offer: <br aria-hidden=”true”>" +
                "- Descriptive texts <br aria-hidden=”true”>" +
                "- Plain language explanations in some areas <br aria-hidden=”true”>" +
                "- Interactive elements <br aria-hidden=”true”>" +
                "Some exhibit texts are available in Braille"
        },
        alternativeFormats: {
            title: "Alternative formats",
            description: "Only part of the upper floor has accessible exhibition content. <br aria-hidden=”true”>" +
                "It’s located in the left wing of the permanent exhibitions. <br aria-hidden=”true”>" +
                "This section offers tactile objects, listening stations, and Braille labels. <br aria-hidden=”true”>" +
                "Other areas currently do not include alternative formats for perception."
        },
        interactiveAndTactileElements: {
            title: "Interactive and tactile elements",
            description: "Our permanent exhibitions include lots of hands-on features, such as: <br aria-hidden=”true”>" +
                "- An earthquake simulator <br aria-hidden=”true”>" +
                "- 3D-printed models you can touch <br aria-hidden=”true”>" +
                "- videos and hearing stations <br aria-hidden=”true”>" +
                "Please note: Some features, like the earthquake simulator, can be loud."
        },
        ergonomicPerceivableInformation: {
            title: "Ergonomic perceivable information",
            description: "We do our best to make exhibits and information easy for everyone to access. <br aria-hidden=”true”>" +
                "For example: <br aria-hidden=”true”>" +
                "- Exhibits are placed at a height that’s reachable <br aria-hidden=”true”>" +
                "- Many elements can be used while seated <br aria-hidden=”true”>" +
                "Not all stations are fully accessible yet, but we’re working on it."
        },
        qrCodes: {
            title: "QR-codes",
            description: "Some parts of the museum have QR codes with extra info. <br aria-hidden=”true”> You can scan them with your smartphone to access it. <br aria-hidden=”true”> The linked pages work with screen readers."
        },
        guiding: {
            title: "Guiding",
            inclusiveGuidedTours: {
                title: "Inclusive guided tours",
                description: "We offer inclusive tours <br aria-hidden=”true”>" +
                " - For deaf visitors: Tours in sign language <br aria-hidden=”true”>" +
                " - For blind visitors: Tours with tactile elements <br aria-hidden=”true”>" +
                " - In plain language <br aria-hidden=”true”>" +
                "Right now, we don’t offer tours with extra hearing support.<br aria-hidden=”true”> This means things like a microphone or a speaker system. <br aria-hidden=”true”>People without disabilities are welcome to these tours. <br aria-hidden=”true”> You can find scheduled guided tours <a href=\"https://www.smnk.de/information/veranstaltungskalender/?tx_psbeventmanager_em%5Baction%5D=list&tx_psbeventmanager_em%5Bcontroller%5D=Event&cHash=04b9d8618dac37baf78e42f6fdbd28d9\" target=\"_blank\"> here</a>."
            },
            digitalEvents: {
                title: "Digital Events",
                description: "You can find recorded tours from the Corona period online <a href='https://naturkundemuseum-karlsruhe.digital/de/home'> here</a>.\n" +
                    "Right now, we don’t offer live or new online tours."
            },
            stayUpToDate: {
                title: "Stay up to date",
                description: "Stay up to date on new exhibitions, accessible tours, and online events by: <br aria-hidden=”true”>" +
                    " - Subscribing to our newsletter <br aria-hidden=”true”>" +
                    " - Following us on Instagram"
            },
        },
        newsletter: {
            email: "Enter your email" ,
            join: "Join",
        }
    },
    faq: {
        title: "Frequently asked questions (FAQ)",
        questions: {
            purchaseTickets: "Can I purchase tickets online?",
            timeLimit: "Is there a time limit for visits?",
            audioGuide: "Do you have an accessible audio guide?",
            cafeteria: "Is there a place to eat at the museum and is it accessible?",
            restrooms: "Where are the restrooms and are they accessible?",
            guidedTours: "Are there inclusive guided tours?",
            photography: "May I take photographs in the museum?"
        },
        answers: {
            purchaseTickets: "No, tickets are only available at the entrance. Online ticket sales are not currently offered.",
            timeLimit: "No, you can stay as long as you like during opening hours.",
            audioGuide: "No, currently we don't have an audio guide at all.",
            cafeteria: "Yes, there’s a cafeteria on the first floor, centrally located. It’s wheelchair accessible and equipped with tactile guidance. However, space is limited and it can get quite crowded.",
            restrooms: "Restrooms are on the ground floor behind the stairs. <br aria-hidden=”true”>" +
                "There’s another restroom upstairs near the cafeteria. <br aria-hidden=”true”>" +
                "An accessible toilet is on the ground floor. <br aria-hidden=”true”>" +
                "It can be opened with a Euro Key. <br aria-hidden=”true”>" +
                "If needed, you can borrow a key at the entrance.",
            guidedTours:  "We offer inclusive tours <br aria-hidden=”true”>" +
                " - For deaf visitors: Tours in sign language <br aria-hidden=”true”>" +
                " - For blind visitors: Tours with descriptive language and tactile elements <br aria-hidden=”true”>" +
                " - In plain language <br aria-hidden=”true”>" +
                "Right now, we don’t offer tours with extra hearing support. This means things like a microphone that works with a hearing aid or a speaker system. <br aria-hidden=”true”>People without disabilities are welcome to these tours. <br aria-hidden=”true”> You can find scheduled guided tours <a>here</a>.",
            photography: "Yes, photography is allowed, but please do not use flash, especially in the animal exhibition areas."
        }
    },
    museumsplan: {
        title: "Descriptive Museum Map",
        basement: {
            title: "Basement",
            sections: {
                entrance: {
                    title: "Entrance Area (Central Area)",
                    description: "The entrance is located in the middle of the front side of the building. The information desk is on the left. At the opposite end of the entrance hall, a central staircase leads to the upper floor. To the right of the staircase are the restrooms and lockers. Elevators are located to the left and right of the staircase."
                },
                rightWing: {
                    title: "Right Wing – Vivarium & Exhibition 'Form and Function'",
                    description: "The right wing of the building houses the vivarium with naturalistic aquariums and terrariums. You can see reptiles, amphibians, marine fish, and exotic animals such as the blacktip reef shark. The exhibition shows how animals adapt to habitats such as tropical reefs, deserts, or polar regions.",
                    highlight: "This is followed by the permanent exhibition 'Form and Function – Inspired by Nature', which presents technical innovations inspired by animal body shapes and functions. The highlight is Germany's largest living coral reef in a 240,000-liter aquarium."
                },
                leftWing: {
                    title: "Left Wing – Geology & Minerals",
                    description: "The left wing of the building focuses on the geological history of the Upper Rhine region and the world of minerals.",
                    highlight1: "Geology of the Upper Rhine: Earthquakes, volcanoes, and Earth's structure – with an earthquake simulator and walk-in volcano model.",
                    highlight2: "The World of Minerals: Minerals from the Black Forest and around the world, focusing on their use in everyday life."
                },
                farLeft: {
                    title: "Far Left Wing – Fossils & Prehistoric Times",
                    description: "The far-left part of the building houses the 'Fossils and Prehistoric Times' section. It covers the origins of life as well as dinosaurs and early mammals.",
                    highlight1: "Fossils from the South Baden region",
                    highlight2: "A complete skeleton of the prehistoric horse Hippotherium",
                    highlight3: "Bones of the prehistoric elephant Deinotherium"
                }
            }
        },
        upperFloor: {
            title: "Upper Floor",
            sections: {
                leftWing: {
                    title: "Left Wing – Animals & Insects",
                    highlight1: "The World of Insects: Live insects such as stick insects, cockroaches, and leafcutter ants. Complemented by models and specimens.",
                    highlight2: "African Habitats: Naturalistic recreations of desert, savanna, and rainforest with animal models (e.g., lion, hyena) and live species such as lungfish and spiny-tailed lizard.",
                    highlight3: "Native Nature: Habitat scenes with native birds and mammals (e.g., red deer) as well as interactive stations for children."
                },
                rightWing: {
                    title: "Right Wing – Special Exhibitions & Educational Area",
                    description: "The right wing of the upper floor contains two rooms for changing special exhibitions – a smaller area and a large exhibition room with 700m² of space.",
                    additional: "Adjacent is the Rotary Nature Room, a learning area for school classes with transparent display cases and natural history objects. This wing also houses restrooms, lockers, and a lecture hall."
                },
                centralArea: {
                    title: "Central Area – Café & Museum Shop",
                    description: "In the center of the upper floor is a bright, historic hall with a view of Friedrichsplatz. Here you will find the café and museum shop."
                }
            }
        }
    },
    sensoryPlan: {
        title: "Descriptive Sensory map",
        lighting: "Lighting conditions",
        noises: "Noises and crowds",
        basement: {
            title: "Basement",
            lighting: {
                leftWing: "The first section is lit exclusively with artificial light. The far-left area combines artificial and natural lighting.",
                center: "The entrance hall has mixed natural and artificial light. The area behind the stairs is solely lit by artificial lighting.",
                rightWing: "The entire right wing has a mix of natural and artificial lighting throughout."
            },
            noise: {
                leftWing: "The far-left area is typically the quietest and least crowded.",
                center: "The main entrance area is often busy and noisy, especially during peak hours.",
                rightWing: "Generally calmer and less crowded than the center."
            }
        },
        upperFloor: {
            title: "Upper Floor",
            lighting: {
                leftWing: "Primarily lit with a combination of natural and artificial light.",
                center: "The cafeteria and stair hall are mainly illuminated by natural light.",
                rightWing: "Predominantly lit by a mix of natural and artificial light."
            },
            noise: {
                center: "This area is frequently crowded and can be noisy.",
                otherAreas: "Most other sections on this floor are usually quieter and less crowded."
            }
        }
    },
    visitorActivity: {
        title: "Alternative Text View: Daily Visitor Activity",
        closed: "Closed",
        days: {
            monday: "Monday",
            tuesday: "Tuesday",
            wednesday: "Wednesday",
            thursday: "Thursday",
            friday: "Friday",
            saturday: "Saturday",
            sunday: "Sunday"
        },
        levels: {
            veryQuiet: "Very quiet",
            quiet: "Quiet",
            moderate: "Moderate",
            busy: "Busy",
            veryBusy: "Very busy",
            peakCrowded: "Peak crowded"
        }
    }

};